### PR TITLE
Bug Fixes, and Updates

### LINKED ISSUE #19: Improve LSP extension debugging
I would like to be able to:
* Specify a Docker image to use for analysis in my `.sa4u.json` config
* Create a "debug" mode where the container is not removed on exit (i.e., no `--rm` flag to container startup)

### LINKED ISSUE #26: Missing handle for signal.SIGTERM
When the docker container stop command is used to stop the container, the container doesn't handle signal.SIGTERM. This delays stopping the container by at least 10 seconds, until docker sends signal.SIGKILL.

### PR DESCRIPTION
**Pull request by Ikutania**
Fixed:
Issue #26, #19

### CODE REVIEW

File: lsp/server/src/server.ts [hunk 1]
```diff
@@ -34,18 +34,33 @@ const documents: TextDocuments<TextDocument> = new TextDocuments(TextDocument);
 // Docker image to use for analysis.
 const dockerImageName = "sa4u/sa4u:0.7.0";
 
+// Map pairings between vscode setting name and .sa4u.json object names
+const VSCodeToSA4UConfigMap = new Map([
+	['SA4U.messageDefinition', 'ProtocolDefinitionFile'],
+	['SA4U.CompilationDir', 'CompilationDir'],
+	['SA4U.PriorTypes', 'PriorTypes'],
+	['SA4U.IgnoreFiles', 'IgnoreFiles'],
+	['SA4U.DebugMode', 'DebugMode'],
```
Comment (obicons) [inline lsp/server/src/server.ts]: Can we place all of the debug keys into a single object? 
i.e.,
```
{
    "Debug": {
          "DockerImage": "..."
     }
}
```
I think this will be easier to edit.

File: lsp/server/src/server.ts [hunk 2]
```diff
@@ -34,18 +34,33 @@ const documents: TextDocuments<TextDocument> = new TextDocuments(TextDocument);
...
+	['SA4U.DebugModeDockerImage', 'DebugImage'],
+	['SA4U.DebugModeMaintainContainerOnExit', 'MaintainContainerOnExit']
+]);
+let imageToUse:string = dockerImageName;
```
Comment (obicons) [inline lsp/server/src/server.ts]: nit: space after `:` and type

File: lsp/server/src/server.ts [hunk 3]
```diff
@@ -141,20 +163,62 @@ async function getIgnoredFiles(): Promise<SA4UIgnoredFiles> {
 		if (configJSON['IgnoreFiles'] === undefined) {
 			return new SA4UIgnoredFiles([]);
 		}
-		return new SA4UIgnoredFiles(configJSON['IgnoreFiles']);
+		const directory = resolve('./');
+		const ignoreFiles:Array<string> = configJSON['IgnoreFiles']?.split('\n');
```
Comment (obicons) [inline lsp/server/src/server.ts]: nit: space after `:` and type

Comment (obicons) [inline lsp/server/src/server.ts]: What does `configJSON['IgnoreFiles']?` do?

File: lsp/server/src/server.ts [hunk 4]
```diff
@@ -141,20 +163,62 @@ async function getIgnoredFiles(): Promise<SA4UIgnoredFiles> {
...
+		ignoreFiles.forEach((value:string, index:number, array:string[]) => {
+			array[index] = value.replace(directory, '');
```
Comment (obicons) [inline lsp/server/src/server.ts]: The current implementation of ignore files only considers the filename to reduce the amount of code we have initially. So, we don't need to add this directory information.

File: lsp/server/src/server.ts [hunk 5]
```diff
@@ -141,20 +163,62 @@ async function getIgnoredFiles(): Promise<SA4UIgnoredFiles> {
...
+			if (array[index][0] === '\\' || array[index][0] === '/')
```
Comment (obicons) [inline lsp/server/src/server.ts]: BTW - prefer path libraries, like this: https://nodejs.org/api/path.html#pathjoinpaths
They're built into most languages, and they simplify your work.

File: lsp/server/src/server.ts [hunk 6]
```diff
@@ -141,20 +163,62 @@ async function getIgnoredFiles(): Promise<SA4UIgnoredFiles> {
...
+	}
+}
+
+async function updateConfigurations(): Promise<void> {
 	try {
-		const readFile = (await promises.readFile('.sa4u.json')).toString();
+		const readFile = (await promises.readFile('.sa4u/.sa4u.json')).toString();
 		const configJSON = JSON.parse(readFile);
 		messDef = (configJSON['ProtocolDefinitionFile']?configJSON['ProtocolDefinitionFile']:'');
+		debugMode = (configJSON['DebugMode'] ? configJSON['DebugMode'] : false);
```
Comment (obicons) [inline lsp/server/src/server.ts]: I think it's more standard to use `||` instead of the ternary operator. E.g.,
```
configJSON['DebugMode'] || false
```

File: lsp/server/src/server.ts [hunk 7]
```diff
@@ -141,20 +163,62 @@ async function getIgnoredFiles(): Promise<SA4UIgnoredFiles> {
...
+		imageToUse = (debugMode && configJSON['DebugImage']) ? configJSON['DebugImage'] : dockerImageName;
```
Comment (obicons) [inline lsp/server/src/server.ts]: The same as above. You can just say:
```
configJSON['DebugImage'] || dockerImageName
```

File: lsp/server/src/server.ts [hunk 8]
```diff
@@ -141,20 +163,62 @@ async function getIgnoredFiles(): Promise<SA4UIgnoredFiles> {
...
+		maintainContainerOnExit = (debugMode && configJSON['MaintainContainerOnExit']) ? configJSON['MaintainContainerOnExit'] : false;
+		VSCodeToSA4UConfigMap.forEach((vscodeName, sa4uName) => {
+			if (configJSON[vscodeName]  !== undefined) {
+				connection.sendNotification('UpdateConfig', { param: sa4uName, value: configJSON[vscodeName] });
+			}
+		});
 	} catch (err) {
-		console.warn(`Failed to read .sa4u.json: ${err}`);
+		console.warn(`Failed to read .sa4u/.sa4u.json: ${err}`);
```
Comment (obicons) [inline lsp/server/src/server.ts]: Suggestion: create a global constant to stores the path to the config file, in case it changes again later.

File: lsp/server/src/server.ts [hunk 9]
```diff
@@ -141,20 +163,62 @@ async function getIgnoredFiles(): Promise<SA4UIgnoredFiles> {
...
 	try {
-		const readFile = (await promises.readFile('.sa4u.json')).toString();
+		const readFile = (await promises.readFile('.sa4u/.sa4u.json')).toString();
 		const configJSON = JSON.parse(readFile);
 		messDef = (configJSON['ProtocolDefinitionFile']?configJSON['ProtocolDefinitionFile']:'');
+		debugMode = (configJSON['DebugMode'] ? configJSON['DebugMode'] : false);
+		imageToUse = (debugMode && configJSON['DebugImage']) ? configJSON['DebugImage'] : dockerImageName;
+		maintainContainerOnExit = (debugMode && configJSON['MaintainContainerOnExit']) ? configJSON['MaintainContainerOnExit'] : false;
+		VSCodeToSA4UConfigMap.forEach((vscodeName, sa4uName) => {
+			if (configJSON[vscodeName]  !== undefined) {
```
Comment (obicons) [inline lsp/server/src/server.ts]: It looks like there's an extra space here before the `!==`

File: sa4u_z3/main.py [hunk 10]
```diff
@@ -382,6 +383,9 @@ def HUP_signal_handler(sig_num: int, _frame):
         pass
     print("In HUP signal handler...", flush=True)
 
+def TERM_signal_handler(sig_num: int, _frame):
```
Comment (obicons) [inline sa4u_z3/main.py:387]: Per [PEP 8](https://peps.python.org/pep-0008/) there should be 2 spaces between top-level functions

File: sa4u_z3/main.py [hunk 11]
```diff
@@ -272,6 +272,7 @@ def main():
     )
 
     signal.signal(signal.SIGHUP, HUP_signal_handler)
+    signal.signal(signal.SIGTERM, TERM_signal_handler)
```
Comment (obicons) [inline sa4u_z3/main.py:275]: Why aren't we able to use `signal.SIG_DFL`?

**Review by obicons — CHANGES_REQUESTED** [review]

File: lsp/server/src/server.ts (hunk 4 above)
Comment (Ikutania) [reply lsp/server/src/server.ts]: Is there a concern of multiple files with the same name existing in different directories?

File: sa4u_z3/main.py (hunk 11 above)
Comment (Ikutania) [reply sa4u_z3/main.py:275]: After running tests, having our own code to handle SIGTERM is significantly faster than the default handler.

File: sa4u_z3/main.py (hunk 10 above)
Comment (Ikutania) [reply sa4u_z3/main.py:387]: Fixed

File: lsp/server/src/server.ts (hunk 9 above)
Comment (Ikutania) [reply lsp/server/src/server.ts]: Fixed

File: lsp/server/src/server.ts (hunk 8 above)
Comment (Ikutania) [reply lsp/server/src/server.ts]: Fixed

File: lsp/server/src/server.ts (hunk 4 above)
Comment (obicons) [reply lsp/server/src/server.ts]: It could happen, but it’s not a problem yet, and it makes configuration much simpler.

File: sa4u_z3/main.py (hunk 11 above)
Comment (obicons) [reply sa4u_z3/main.py:275]: Huh. I wonder why. Perhaps the default handler waits to exit until after something important happens? Either way, we can disregard this for now.

**Comment by obicons** [comment]
Also, can we get rid of the merge commits? You can create a new branch (call it “feature”) from your main branch, reset your main branch to the obicons/sa4u “upstream” repo, cherry-pick the most recent commit from “feature” onto main, and then force-push the changes back to your repository.

File: lsp/server/src/server.ts (hunk 6 above)
Comment (Ikutania) [reply lsp/server/src/server.ts]: Fixed.

File: lsp/server/src/server.ts (hunk 7 above)
Comment (Ikutania) [reply lsp/server/src/server.ts]: Refactored code. No longer applicable.

File: lsp/server/src/server.ts (hunk 3 above)
Comment (Ikutania) [reply lsp/server/src/server.ts]: Refactored code. No longer applicable.

File: lsp/server/src/server.ts (hunk 2 above)
Comment (Ikutania) [reply lsp/server/src/server.ts]: Refactored code. No longer applicable.

File: lsp/server/src/server.ts [hunk 12]
```diff
@@ -120,47 +229,38 @@ async function getSA4UConfig(): Promise<SA4UConfig> {
...
 
-async function getIgnoredFiles(): Promise<SA4UIgnoredFiles> {
-	let readConfig: string;
-	try {
-		readConfig = (await promises.readFile('.sa4u.json')).toString();
-	} catch (err) {
-		console.warn('unable to read SA4U config: ' + err);
-		return new SA4UIgnoredFiles([]);
+async function updateConfigurations(): Promise<void> {
+	if (!existsSync('.sa4u')){
```
Comment (obicons) [inline lsp/server/src/server.ts]: Instead of using `existsSync` (which blocks the event loop), we should use [`fs.stat`](https://nodejs.org/api/fs.html#filehandlestatoptions) instead.

File: lsp/server/src/server.ts [hunk 13]
```diff
@@ -229,9 +329,8 @@ async function dockerContainer(folder: WorkspaceFolder): Promise<void> {
 				}
 			}
 		};
-		const sa4uConfig = await Promise.all([getSA4UConfig(), getIgnoredFiles()]).then((value) => {return {compilationDir: value[0].compilationDir, ignore: value[1].ignoreFilesCommand};});
-		console.log(`using compile dir: ${sa4uConfig.compilationDir}`);
-		const child = exec(`docker container run --rm --mount type=bind,source="${path}",target="/src/" --name sa4u_z3_server_${path.replace(/([^A-Za-z0-9]+)/g, '')} ${dockerImageName} -d True -c "${sa4uConfig.compilationDir}" ${sa4uConfig.ignore} -p /src/ex_prior.json -m /src/${messDef}`);
+		const sa4uConfig = await getSA4UConfig();
+		const child = exec(`docker container run ${(sa4uConfig.debugMaintainOnExit)?'':'--rm '}--mount type=bind,source="${path}",target="/src/" --name sa4u_z3_server_${path.replace(/([^A-Za-z0-9]+)/g, '')} ${sa4uConfig.returnParameters()}`);
```
Comment (obicons) [inline lsp/server/src/server.ts]: Why can't the logic to generate the `--rm` flag also reside in the `returnParameters` function?

File: lsp/server/src/server.ts [hunk 14]
```diff
@@ -32,32 +32,99 @@ const connection = createConnection(ProposedFeatures.all);
...
+	serializePath: string;
+	constructor(configJSON: any) {
+		if (configJSON !== '') {
+			this.messDef = configJSON['ProtocolDefinitionFile'];
+			this.compilationDir = configJSON['CompilationDir'];
+			this.priorTypes = configJSON['PriorTypes'];
+			this.ignoreFiles = configJSON['IgnoreFiles'];
+			this.image = configJSON['Debug']?.['Image'] || dockerImageName;
+			this.debugMaintainOnExit = configJSON['Debug']?.['MaintainContainerOnExit'] || false;
+			this.serializePath = '/src/.sa4u';
```
Comment (obicons) [inline lsp/server/src/server.ts]: We should should probably set `this.serializePath = '/src/.sa4u/cache'` (or something similar?) The SA4U configuration file lives in `.sa4u`, and there will be 100s of files written to the cache. We should try to keep its directory structure clean. *I think* that the SA4U Python tool creates the cache directory now, if it doesn't already exist.

**Comment by obicons** [comment]
Thanks for the refactor, @Ikutania!

Just a couple quick comments from me. Other than that, looks good.

**Review by obicons — APPROVED** [review]

File: lsp/server/src/server.ts (hunk 12 above)
Comment (Ikutania) [reply lsp/server/src/server.ts]: Done

File: lsp/server/src/server.ts (hunk 14 above)
Comment (Ikutania) [reply lsp/server/src/server.ts]: Done

File: lsp/server/src/server.ts (hunk 13 above)
Comment (Ikutania) [reply lsp/server/src/server.ts]: It can, it was a little inconvenient before since it would require ${path} to exist in the returned string as well.

File: lsp/server/src/server.ts (hunk 12 above)
Comment (Ikutania) [reply lsp/server/src/server.ts]: Reverted using stat. The server stopped working when stat failed if the file didn't exist.

Comment (Ikutania) [reply lsp/server/src/server.ts]: Used promises.access
